; generated by gcode_3d.py on 2026-02-22 at 12:11:00 UTC
; prusaslicer:gcode_flavor = marlin2
; prusaslicer:printer_model = MK3S
; layer_count = 4
; ============================================================
; 3D LEGO G-code  —  generated by gcode_3d.py
; Structure  : 4 wide × 4 deep × 4 tall  (Minecraft X/Z/Y)
; Physical   : 32 mm × 32 mm × 38 mm
; Bricks     : 20 total (all RED)
; Origin     : X=64.0  Y=32.0  Z=0.0
; Dispenser  : X=24.0  Y=0.0  Z=3.4
; ============================================================

M73 P0 R0 Q0 S0        ; progress: 0%
M201 X1000 Y1000 Z200  ; max accelerations [mm/s^2]
M203 X200 Y200 Z12     ; max feedrates [mm/s]
M204 P1250 T1250       ; print / travel acceleration [mm/s^2]
M205 X8.00 Y8.00 Z0.40 ; jerk limits [mm/s]
G21                    ; units: millimetres
G90                    ; absolute positioning
G28 X Y                ; home X and Y
G92 X-11 Y-7           ; offset origin to working zero
G92 Z3.8               ; declare current Z (manually parked before run)
M211 S0                ; disable software endstops — allow negative Z
M83                    ; relative extruder mode
G92 E0                 ; reset extruder position

G0 Z70.000 F20000 ; raise to safe travel height
;TYPE:Travel

;LAYER_CHANGE
;Z:0.000
;HEIGHT:9.600
; --- Layer 1/4 ---
M73 P0 R0 Q0 S0  ; progress 0%
; ── Brick    1/20  col_x=3  col_y=0  row=0  →  X=112.0  Y=32.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y32.000 E0.0500 F12000 ; position over col_x=3 col_y=0 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P5 R0 Q5 S0  ; progress 5%
; ── Brick    2/20  col_x=2  col_y=1  row=0  →  X=96.0  Y=40.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X96.000 Y40.000 E0.0500 F12000 ; position over col_x=2 col_y=1 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P10 R0 Q10 S0  ; progress 10%
; ── Brick    3/20  col_x=3  col_y=1  row=0  →  X=112.0  Y=40.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y40.000 E0.0500 F12000 ; position over col_x=3 col_y=1 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P15 R0 Q15 S0  ; progress 15%
; ── Brick    4/20  col_x=1  col_y=2  row=0  →  X=80.0  Y=48.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X80.000 Y48.000 E0.0500 F12000 ; position over col_x=1 col_y=2 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P20 R0 Q20 S0  ; progress 20%
; ── Brick    5/20  col_x=2  col_y=2  row=0  →  X=96.0  Y=48.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X96.000 Y48.000 E0.0500 F12000 ; position over col_x=2 col_y=2 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P25 R0 Q25 S0  ; progress 25%
; ── Brick    6/20  col_x=3  col_y=2  row=0  →  X=112.0  Y=48.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y48.000 E0.0500 F12000 ; position over col_x=3 col_y=2 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P30 R0 Q30 S0  ; progress 30%
; ── Brick    7/20  col_x=0  col_y=3  row=0  →  X=64.0  Y=56.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X64.000 Y56.000 E0.0500 F12000 ; position over col_x=0 col_y=3 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P35 R0 Q35 S0  ; progress 35%
; ── Brick    8/20  col_x=1  col_y=3  row=0  →  X=80.0  Y=56.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X80.000 Y56.000 E0.0500 F12000 ; position over col_x=1 col_y=3 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P40 R0 Q40 S0  ; progress 40%
; ── Brick    9/20  col_x=2  col_y=3  row=0  →  X=96.0  Y=56.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X96.000 Y56.000 E0.0500 F12000 ; position over col_x=2 col_y=3 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P45 R0 Q45 S0  ; progress 45%
; ── Brick   10/20  col_x=3  col_y=3  row=0  →  X=112.0  Y=56.0  Z=0.0 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y56.000 E0.0500 F12000 ; position over col_x=3 col_y=3 row=0
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z6.000 F4000 ; slow approach (6 mm above target)
G1 Z0.000 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

;LAYER_CHANGE
;Z:9.600
;HEIGHT:9.600
; --- Layer 2/4 ---
M73 P50 R0 Q50 S0  ; progress 50%
; ── Brick   11/20  col_x=3  col_y=1  row=1  →  X=112.0  Y=40.0  Z=9.6 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y40.000 E0.0500 F12000 ; position over col_x=3 col_y=1 row=1
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z15.600 F4000 ; slow approach (6 mm above target)
G1 Z9.600 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P55 R0 Q55 S0  ; progress 55%
; ── Brick   12/20  col_x=2  col_y=2  row=1  →  X=96.0  Y=48.0  Z=9.6 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X96.000 Y48.000 E0.0500 F12000 ; position over col_x=2 col_y=2 row=1
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z15.600 F4000 ; slow approach (6 mm above target)
G1 Z9.600 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P60 R0 Q60 S0  ; progress 60%
; ── Brick   13/20  col_x=3  col_y=2  row=1  →  X=112.0  Y=48.0  Z=9.6 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y48.000 E0.0500 F12000 ; position over col_x=3 col_y=2 row=1
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z15.600 F4000 ; slow approach (6 mm above target)
G1 Z9.600 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P65 R0 Q65 S0  ; progress 65%
; ── Brick   14/20  col_x=1  col_y=3  row=1  →  X=80.0  Y=56.0  Z=9.6 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X80.000 Y56.000 E0.0500 F12000 ; position over col_x=1 col_y=3 row=1
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z15.600 F4000 ; slow approach (6 mm above target)
G1 Z9.600 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P70 R0 Q70 S0  ; progress 70%
; ── Brick   15/20  col_x=2  col_y=3  row=1  →  X=96.0  Y=56.0  Z=9.6 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X96.000 Y56.000 E0.0500 F12000 ; position over col_x=2 col_y=3 row=1
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z15.600 F4000 ; slow approach (6 mm above target)
G1 Z9.600 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P75 R0 Q75 S0  ; progress 75%
; ── Brick   16/20  col_x=3  col_y=3  row=1  →  X=112.0  Y=56.0  Z=9.6 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y56.000 E0.0500 F12000 ; position over col_x=3 col_y=3 row=1
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z15.600 F4000 ; slow approach (6 mm above target)
G1 Z9.600 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

;LAYER_CHANGE
;Z:19.200
;HEIGHT:9.600
; --- Layer 3/4 ---
M73 P80 R0 Q80 S0  ; progress 80%
; ── Brick   17/20  col_x=3  col_y=2  row=2  →  X=112.0  Y=48.0  Z=19.2 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y48.000 E0.0500 F12000 ; position over col_x=3 col_y=2 row=2
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z25.200 F4000 ; slow approach (6 mm above target)
G1 Z19.200 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P85 R0 Q85 S0  ; progress 85%
; ── Brick   18/20  col_x=2  col_y=3  row=2  →  X=96.0  Y=56.0  Z=19.2 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X96.000 Y56.000 E0.0500 F12000 ; position over col_x=2 col_y=3 row=2
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z25.200 F4000 ; slow approach (6 mm above target)
G1 Z19.200 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P90 R0 Q90 S0  ; progress 90%
; ── Brick   19/20  col_x=3  col_y=3  row=2  →  X=112.0  Y=56.0  Z=19.2 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y56.000 E0.0500 F12000 ; position over col_x=3 col_y=3 row=2
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z25.200 F4000 ; slow approach (6 mm above target)
G1 Z19.200 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

;LAYER_CHANGE
;Z:28.800
;HEIGHT:9.600
; --- Layer 4/4 ---
M73 P95 R0 Q95 S0  ; progress 95%
; ── Brick   20/20  col_x=3  col_y=3  row=3  →  X=112.0  Y=56.0  Z=28.8 ──
;    [pick-up RED]
;TYPE:Travel
G0 X24.000 Y0.000 F20000 ; move over RED dispenser
G0 Z3.400 F4000 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z70.000 F12000 ; rise with brick

;    [travel to brick]
;TYPE:Custom
G1 X112.000 Y56.000 E0.0500 F12000 ; position over col_x=3 col_y=3 row=3
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z34.800 F4000 ; slow approach (6 mm above target)
G1 Z28.800 F500 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z70.000 F20000 ; retract to travel height

M73 P100 R0 Q100 S0  ; progress: 100%

; ── All bricks placed ──────────────────────────────────────
;TYPE:Travel
G1 Z80.000 F720 ; raise nozzle clear of structure
M211 S1      ; re-enable software endstops
M84          ; disable steppers
