; generated by PrusaSlicer 2.7.4 on 2026-02-21 at 21:57:55 UTC
; prusaslicer:gcode_flavor = marlin2
; prusaslicer:printer_model = MK3S
; layer_count = 5
; estimated printing time (normal mode) = 0s
; filament used [mm] = 0
; nozzle_diameter = 0
; total_toolchanges = 0
; ============================================================
; LEGO Wall G-code  —  generated by nbt_to_gcode.py
; Structure  : 12 cols wide × 5 rows tall
; Bricks     : 60 total  (18 red, 42 yellow)
; Brick size : 16.0 mm × 9.6 mm (W × H)
; Wall X     : 50.0 – 242.0 mm
; Wall Z     : 5.0 – 53.0 mm
; Disp RED   : X=0.0  Y=0.0  Z=5.0
; Disp YELLOW: X=30.0  Y=0.0  Z=5.0
; ============================================================

M73 P0 R0 Q0 S0        ; progress: 0% (normal + stealth modes)
M201 X1000 Y1000 Z200  ; max accelerations [mm/s^2] — no E (no extruder)
M203 X200 Y200 Z12     ; max feedrates [mm/s]
M204 P1250 T1250       ; print / travel acceleration [mm/s^2]
M205 X8.00 Y8.00 Z0.40 ; jerk limits [mm/s]
G21                    ; units: millimetres
G90                    ; absolute positioning
G28 W                  ; home all axes (W = skip mesh bed leveling)
; NOTE: M104/M109/M140/M190 omitted — no hotend/bed on this machine

G0 Z80.000 F6000 ; raise to safe travel height
;TYPE:Travel

;LAYER_CHANGE
;Z:5.000
;HEIGHT:9.600
; --- Layer 1/5 ---
M73 P0 R0 Q0 S0  ; progress 0%
; ── Brick    1/60  [YELLOW]  col=  0  row=  0  →  X=50.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X50.000 Y150.000 F6000 ; position over col=0 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P2 R0 Q2 S0  ; progress 2%
; ── Brick    2/60  [YELLOW]  col=  1  row=  0  →  X=66.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X66.000 Y150.000 F6000 ; position over col=1 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P3 R0 Q3 S0  ; progress 3%
; ── Brick    3/60  [RED   ]  col=  2  row=  0  →  X=82.0  Z=5.0 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X82.000 Y150.000 F6000 ; position over col=2 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P5 R0 Q5 S0  ; progress 5%
; ── Brick    4/60  [YELLOW]  col=  3  row=  0  →  X=98.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X98.000 Y150.000 F6000 ; position over col=3 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P7 R0 Q7 S0  ; progress 7%
; ── Brick    5/60  [RED   ]  col=  4  row=  0  →  X=114.0  Z=5.0 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X114.000 Y150.000 F6000 ; position over col=4 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P8 R0 Q8 S0  ; progress 8%
; ── Brick    6/60  [YELLOW]  col=  5  row=  0  →  X=130.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X130.000 Y150.000 F6000 ; position over col=5 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P10 R0 Q10 S0  ; progress 10%
; ── Brick    7/60  [RED   ]  col=  6  row=  0  →  X=146.0  Z=5.0 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X146.000 Y150.000 F6000 ; position over col=6 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P12 R0 Q12 S0  ; progress 12%
; ── Brick    8/60  [YELLOW]  col=  7  row=  0  →  X=162.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X162.000 Y150.000 F6000 ; position over col=7 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P13 R0 Q13 S0  ; progress 13%
; ── Brick    9/60  [YELLOW]  col=  8  row=  0  →  X=178.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X178.000 Y150.000 F6000 ; position over col=8 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P15 R0 Q15 S0  ; progress 15%
; ── Brick   10/60  [YELLOW]  col=  9  row=  0  →  X=194.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X194.000 Y150.000 F6000 ; position over col=9 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P17 R0 Q17 S0  ; progress 17%
; ── Brick   11/60  [RED   ]  col= 10  row=  0  →  X=210.0  Z=5.0 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X210.000 Y150.000 F6000 ; position over col=10 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P18 R0 Q18 S0  ; progress 18%
; ── Brick   12/60  [YELLOW]  col= 11  row=  0  →  X=226.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X226.000 Y150.000 F6000 ; position over col=11 row=0

;    [place]
;TYPE:Custom
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

;LAYER_CHANGE
;Z:14.600
;HEIGHT:9.600
; --- Layer 2/5 ---
M73 P20 R0 Q20 S0  ; progress 20%
; ── Brick   13/60  [YELLOW]  col=  0  row=  1  →  X=50.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X50.000 Y150.000 F6000 ; position over col=0 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P22 R0 Q22 S0  ; progress 22%
; ── Brick   14/60  [YELLOW]  col=  1  row=  1  →  X=66.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X66.000 Y150.000 F6000 ; position over col=1 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P23 R0 Q23 S0  ; progress 23%
; ── Brick   15/60  [RED   ]  col=  2  row=  1  →  X=82.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X82.000 Y150.000 F6000 ; position over col=2 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P25 R0 Q25 S0  ; progress 25%
; ── Brick   16/60  [YELLOW]  col=  3  row=  1  →  X=98.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X98.000 Y150.000 F6000 ; position over col=3 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P27 R0 Q27 S0  ; progress 27%
; ── Brick   17/60  [RED   ]  col=  4  row=  1  →  X=114.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X114.000 Y150.000 F6000 ; position over col=4 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P28 R0 Q28 S0  ; progress 28%
; ── Brick   18/60  [YELLOW]  col=  5  row=  1  →  X=130.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X130.000 Y150.000 F6000 ; position over col=5 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P30 R0 Q30 S0  ; progress 30%
; ── Brick   19/60  [RED   ]  col=  6  row=  1  →  X=146.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X146.000 Y150.000 F6000 ; position over col=6 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P32 R0 Q32 S0  ; progress 32%
; ── Brick   20/60  [YELLOW]  col=  7  row=  1  →  X=162.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X162.000 Y150.000 F6000 ; position over col=7 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P33 R0 Q33 S0  ; progress 33%
; ── Brick   21/60  [RED   ]  col=  8  row=  1  →  X=178.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X178.000 Y150.000 F6000 ; position over col=8 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P35 R0 Q35 S0  ; progress 35%
; ── Brick   22/60  [YELLOW]  col=  9  row=  1  →  X=194.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X194.000 Y150.000 F6000 ; position over col=9 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P37 R0 Q37 S0  ; progress 37%
; ── Brick   23/60  [RED   ]  col= 10  row=  1  →  X=210.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X210.000 Y150.000 F6000 ; position over col=10 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P38 R0 Q38 S0  ; progress 38%
; ── Brick   24/60  [YELLOW]  col= 11  row=  1  →  X=226.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X226.000 Y150.000 F6000 ; position over col=11 row=1

;    [place]
;TYPE:Custom
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

;LAYER_CHANGE
;Z:24.200
;HEIGHT:9.600
; --- Layer 3/5 ---
M73 P40 R0 Q40 S0  ; progress 40%
; ── Brick   25/60  [YELLOW]  col=  0  row=  2  →  X=50.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X50.000 Y150.000 F6000 ; position over col=0 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P42 R0 Q42 S0  ; progress 42%
; ── Brick   26/60  [YELLOW]  col=  1  row=  2  →  X=66.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X66.000 Y150.000 F6000 ; position over col=1 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P43 R0 Q43 S0  ; progress 43%
; ── Brick   27/60  [YELLOW]  col=  2  row=  2  →  X=82.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X82.000 Y150.000 F6000 ; position over col=2 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P45 R0 Q45 S0  ; progress 45%
; ── Brick   28/60  [YELLOW]  col=  3  row=  2  →  X=98.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X98.000 Y150.000 F6000 ; position over col=3 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P47 R0 Q47 S0  ; progress 47%
; ── Brick   29/60  [YELLOW]  col=  4  row=  2  →  X=114.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X114.000 Y150.000 F6000 ; position over col=4 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P48 R0 Q48 S0  ; progress 48%
; ── Brick   30/60  [YELLOW]  col=  5  row=  2  →  X=130.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X130.000 Y150.000 F6000 ; position over col=5 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P50 R0 Q50 S0  ; progress 50%
; ── Brick   31/60  [RED   ]  col=  6  row=  2  →  X=146.0  Z=24.2 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X146.000 Y150.000 F6000 ; position over col=6 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P52 R0 Q52 S0  ; progress 52%
; ── Brick   32/60  [YELLOW]  col=  7  row=  2  →  X=162.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X162.000 Y150.000 F6000 ; position over col=7 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P53 R0 Q53 S0  ; progress 53%
; ── Brick   33/60  [RED   ]  col=  8  row=  2  →  X=178.0  Z=24.2 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X178.000 Y150.000 F6000 ; position over col=8 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P55 R0 Q55 S0  ; progress 55%
; ── Brick   34/60  [YELLOW]  col=  9  row=  2  →  X=194.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X194.000 Y150.000 F6000 ; position over col=9 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P57 R0 Q57 S0  ; progress 57%
; ── Brick   35/60  [RED   ]  col= 10  row=  2  →  X=210.0  Z=24.2 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X210.000 Y150.000 F6000 ; position over col=10 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P58 R0 Q58 S0  ; progress 58%
; ── Brick   36/60  [YELLOW]  col= 11  row=  2  →  X=226.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X226.000 Y150.000 F6000 ; position over col=11 row=2

;    [place]
;TYPE:Custom
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

;LAYER_CHANGE
;Z:33.800
;HEIGHT:9.600
; --- Layer 4/5 ---
M73 P60 R0 Q60 S0  ; progress 60%
; ── Brick   37/60  [YELLOW]  col=  0  row=  3  →  X=50.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X50.000 Y150.000 F6000 ; position over col=0 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P62 R0 Q62 S0  ; progress 62%
; ── Brick   38/60  [RED   ]  col=  1  row=  3  →  X=66.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X66.000 Y150.000 F6000 ; position over col=1 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P63 R0 Q63 S0  ; progress 63%
; ── Brick   39/60  [RED   ]  col=  2  row=  3  →  X=82.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X82.000 Y150.000 F6000 ; position over col=2 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P65 R0 Q65 S0  ; progress 65%
; ── Brick   40/60  [YELLOW]  col=  3  row=  3  →  X=98.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X98.000 Y150.000 F6000 ; position over col=3 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P67 R0 Q67 S0  ; progress 67%
; ── Brick   41/60  [RED   ]  col=  4  row=  3  →  X=114.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X114.000 Y150.000 F6000 ; position over col=4 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P68 R0 Q68 S0  ; progress 68%
; ── Brick   42/60  [YELLOW]  col=  5  row=  3  →  X=130.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X130.000 Y150.000 F6000 ; position over col=5 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P70 R0 Q70 S0  ; progress 70%
; ── Brick   43/60  [RED   ]  col=  6  row=  3  →  X=146.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X146.000 Y150.000 F6000 ; position over col=6 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P72 R0 Q72 S0  ; progress 72%
; ── Brick   44/60  [YELLOW]  col=  7  row=  3  →  X=162.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X162.000 Y150.000 F6000 ; position over col=7 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P73 R0 Q73 S0  ; progress 73%
; ── Brick   45/60  [RED   ]  col=  8  row=  3  →  X=178.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X178.000 Y150.000 F6000 ; position over col=8 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P75 R0 Q75 S0  ; progress 75%
; ── Brick   46/60  [YELLOW]  col=  9  row=  3  →  X=194.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X194.000 Y150.000 F6000 ; position over col=9 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P77 R0 Q77 S0  ; progress 77%
; ── Brick   47/60  [RED   ]  col= 10  row=  3  →  X=210.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X210.000 Y150.000 F6000 ; position over col=10 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P78 R0 Q78 S0  ; progress 78%
; ── Brick   48/60  [YELLOW]  col= 11  row=  3  →  X=226.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X226.000 Y150.000 F6000 ; position over col=11 row=3

;    [place]
;TYPE:Custom
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

;LAYER_CHANGE
;Z:43.400
;HEIGHT:9.600
; --- Layer 5/5 ---
M73 P80 R0 Q80 S0  ; progress 80%
; ── Brick   49/60  [YELLOW]  col=  0  row=  4  →  X=50.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X50.000 Y150.000 F6000 ; position over col=0 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P82 R0 Q82 S0  ; progress 82%
; ── Brick   50/60  [YELLOW]  col=  1  row=  4  →  X=66.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X66.000 Y150.000 F6000 ; position over col=1 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P83 R0 Q83 S0  ; progress 83%
; ── Brick   51/60  [YELLOW]  col=  2  row=  4  →  X=82.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X82.000 Y150.000 F6000 ; position over col=2 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P85 R0 Q85 S0  ; progress 85%
; ── Brick   52/60  [YELLOW]  col=  3  row=  4  →  X=98.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X98.000 Y150.000 F6000 ; position over col=3 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P87 R0 Q87 S0  ; progress 87%
; ── Brick   53/60  [YELLOW]  col=  4  row=  4  →  X=114.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X114.000 Y150.000 F6000 ; position over col=4 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P88 R0 Q88 S0  ; progress 88%
; ── Brick   54/60  [YELLOW]  col=  5  row=  4  →  X=130.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X130.000 Y150.000 F6000 ; position over col=5 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P90 R0 Q90 S0  ; progress 90%
; ── Brick   55/60  [YELLOW]  col=  6  row=  4  →  X=146.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X146.000 Y150.000 F6000 ; position over col=6 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P92 R0 Q92 S0  ; progress 92%
; ── Brick   56/60  [YELLOW]  col=  7  row=  4  →  X=162.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X162.000 Y150.000 F6000 ; position over col=7 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P93 R0 Q93 S0  ; progress 93%
; ── Brick   57/60  [YELLOW]  col=  8  row=  4  →  X=178.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X178.000 Y150.000 F6000 ; position over col=8 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P95 R0 Q95 S0  ; progress 95%
; ── Brick   58/60  [YELLOW]  col=  9  row=  4  →  X=194.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X194.000 Y150.000 F6000 ; position over col=9 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P97 R0 Q97 S0  ; progress 97%
; ── Brick   59/60  [YELLOW]  col= 10  row=  4  →  X=210.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X210.000 Y150.000 F6000 ; position over col=10 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P98 R0 Q98 S0  ; progress 98%
; ── Brick   60/60  [YELLOW]  col= 11  row=  4  →  X=226.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F6000 ; rise with brick

;    [travel]
;TYPE:Travel
G0 X226.000 Y150.000 F6000 ; position over col=11 row=4

;    [place]
;TYPE:Custom
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P100 R0 Q100 S0  ; progress: 100%

; ── All bricks placed ──────────────────────────────────────
;TYPE:Travel
G1 Z90.000 F720 ; raise nozzle before end
G0 X0.000 Y200.000 F3000 ; present build plate
; NOTE: M104 S0 / M140 S0 / M107 omitted — no hotend/bed on this machine
M84          ; disable steppers