; generated by PrusaSlicer 2.9.4 on 2026-02-22 at 00:46:31 UTC
; prusaslicer:gcode_flavor = marlin2
; prusaslicer:printer_model = MK3S
; layer_count = 5
; estimated printing time (normal mode) = 0s
; filament used [mm] = 0
; nozzle_diameter = 0
; total_toolchanges = 0
; ============================================================
; LEGO Wall G-code  —  generated by nbt_to_gcode.py
; Structure  : 12 cols wide × 5 rows tall
; Bricks     : 60 total  (18 red, 42 yellow)
; Brick face : 8 mm wide × 9.6 mm tall  (short / square end faces out)
; Wall depth : 16 mm  (2 studs — long axis of brick points inward)
; Wall X     : 50.0 – 146.0 mm
; Wall Z     : 5.0 – 53.0 mm
; Disp RED   : X=0.0  Y=0.0  Z=5.0
; Disp YELLOW: X=30.0  Y=0.0  Z=5.0
; ============================================================

M73 P0 R0 Q0 S0        ; progress: 0% (normal + stealth modes)
M201 X1000 Y1000 Z200  ; max accelerations [mm/s^2] — no E (no extruder)
M203 X200 Y200 Z12     ; max feedrates [mm/s]
M204 P1250 T1250       ; print / travel acceleration [mm/s^2]
M205 X8.00 Y8.00 Z0.40 ; jerk limits [mm/s]
G21                    ; units: millimetres
G90                    ; absolute positioning
G28 W                  ; home all axes (W = skip mesh bed leveling)
; NOTE: M104/M109/M140/M190 omitted — no hotend/bed on this machine
M83                    ; relative extruder mode (E values are incremental)
G92 E0                 ; reset extruder position

G0 Z80.000 F6000 ; raise to safe travel height
;TYPE:Travel

;LAYER_CHANGE
;Z:5.000
;HEIGHT:9.600
; --- Layer 1/5 ---
M73 P0 R0 Q0 S0  ; progress 0%
; ── Brick    1/60  [YELLOW]  col=  0  row=  0  →  X=50.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X50.000 Y150.000 E0.0500 F2000 ; position over col=0 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P2 R0 Q2 S0  ; progress 2%
; ── Brick    2/60  [YELLOW]  col=  1  row=  0  →  X=58.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X58.000 Y150.000 E0.0500 F2000 ; position over col=1 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P3 R0 Q3 S0  ; progress 3%
; ── Brick    3/60  [RED   ]  col=  2  row=  0  →  X=66.0  Z=5.0 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X66.000 Y150.000 E0.0500 F2000 ; position over col=2 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P5 R0 Q5 S0  ; progress 5%
; ── Brick    4/60  [YELLOW]  col=  3  row=  0  →  X=74.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X74.000 Y150.000 E0.0500 F2000 ; position over col=3 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P7 R0 Q7 S0  ; progress 7%
; ── Brick    5/60  [RED   ]  col=  4  row=  0  →  X=82.0  Z=5.0 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X82.000 Y150.000 E0.0500 F2000 ; position over col=4 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P8 R0 Q8 S0  ; progress 8%
; ── Brick    6/60  [YELLOW]  col=  5  row=  0  →  X=90.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X90.000 Y150.000 E0.0500 F2000 ; position over col=5 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P10 R0 Q10 S0  ; progress 10%
; ── Brick    7/60  [RED   ]  col=  6  row=  0  →  X=98.0  Z=5.0 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X98.000 Y150.000 E0.0500 F2000 ; position over col=6 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P12 R0 Q12 S0  ; progress 12%
; ── Brick    8/60  [YELLOW]  col=  7  row=  0  →  X=106.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X106.000 Y150.000 E0.0500 F2000 ; position over col=7 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P13 R0 Q13 S0  ; progress 13%
; ── Brick    9/60  [YELLOW]  col=  8  row=  0  →  X=114.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X114.000 Y150.000 E0.0500 F2000 ; position over col=8 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P15 R0 Q15 S0  ; progress 15%
; ── Brick   10/60  [YELLOW]  col=  9  row=  0  →  X=122.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X122.000 Y150.000 E0.0500 F2000 ; position over col=9 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P17 R0 Q17 S0  ; progress 17%
; ── Brick   11/60  [RED   ]  col= 10  row=  0  →  X=130.0  Z=5.0 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X130.000 Y150.000 E0.0500 F2000 ; position over col=10 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P18 R0 Q18 S0  ; progress 18%
; ── Brick   12/60  [YELLOW]  col= 11  row=  0  →  X=138.0  Z=5.0 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X138.000 Y150.000 E0.0500 F2000 ; position over col=11 row=0 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z29.500 F800 ; slow approach (6 mm above target)
G1 Z23.500 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

;LAYER_CHANGE
;Z:14.600
;HEIGHT:9.600
; --- Layer 2/5 ---
M73 P20 R0 Q20 S0  ; progress 20%
; ── Brick   13/60  [YELLOW]  col=  0  row=  1  →  X=50.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X50.000 Y150.000 E0.0500 F2000 ; position over col=0 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P22 R0 Q22 S0  ; progress 22%
; ── Brick   14/60  [YELLOW]  col=  1  row=  1  →  X=58.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X58.000 Y150.000 E0.0500 F2000 ; position over col=1 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P23 R0 Q23 S0  ; progress 23%
; ── Brick   15/60  [RED   ]  col=  2  row=  1  →  X=66.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X66.000 Y150.000 E0.0500 F2000 ; position over col=2 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P25 R0 Q25 S0  ; progress 25%
; ── Brick   16/60  [YELLOW]  col=  3  row=  1  →  X=74.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X74.000 Y150.000 E0.0500 F2000 ; position over col=3 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P27 R0 Q27 S0  ; progress 27%
; ── Brick   17/60  [RED   ]  col=  4  row=  1  →  X=82.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X82.000 Y150.000 E0.0500 F2000 ; position over col=4 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P28 R0 Q28 S0  ; progress 28%
; ── Brick   18/60  [YELLOW]  col=  5  row=  1  →  X=90.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X90.000 Y150.000 E0.0500 F2000 ; position over col=5 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P30 R0 Q30 S0  ; progress 30%
; ── Brick   19/60  [RED   ]  col=  6  row=  1  →  X=98.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X98.000 Y150.000 E0.0500 F2000 ; position over col=6 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P32 R0 Q32 S0  ; progress 32%
; ── Brick   20/60  [YELLOW]  col=  7  row=  1  →  X=106.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X106.000 Y150.000 E0.0500 F2000 ; position over col=7 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P33 R0 Q33 S0  ; progress 33%
; ── Brick   21/60  [RED   ]  col=  8  row=  1  →  X=114.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X114.000 Y150.000 E0.0500 F2000 ; position over col=8 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P35 R0 Q35 S0  ; progress 35%
; ── Brick   22/60  [YELLOW]  col=  9  row=  1  →  X=122.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X122.000 Y150.000 E0.0500 F2000 ; position over col=9 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P37 R0 Q37 S0  ; progress 37%
; ── Brick   23/60  [RED   ]  col= 10  row=  1  →  X=130.0  Z=14.6 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X130.000 Y150.000 E0.0500 F2000 ; position over col=10 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P38 R0 Q38 S0  ; progress 38%
; ── Brick   24/60  [YELLOW]  col= 11  row=  1  →  X=138.0  Z=14.6 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X138.000 Y150.000 E0.0500 F2000 ; position over col=11 row=1 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z39.100 F800 ; slow approach (6 mm above target)
G1 Z33.100 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

;LAYER_CHANGE
;Z:24.200
;HEIGHT:9.600
; --- Layer 3/5 ---
M73 P40 R0 Q40 S0  ; progress 40%
; ── Brick   25/60  [YELLOW]  col=  0  row=  2  →  X=50.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X50.000 Y150.000 E0.0500 F2000 ; position over col=0 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P42 R0 Q42 S0  ; progress 42%
; ── Brick   26/60  [YELLOW]  col=  1  row=  2  →  X=58.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X58.000 Y150.000 E0.0500 F2000 ; position over col=1 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P43 R0 Q43 S0  ; progress 43%
; ── Brick   27/60  [YELLOW]  col=  2  row=  2  →  X=66.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X66.000 Y150.000 E0.0500 F2000 ; position over col=2 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P45 R0 Q45 S0  ; progress 45%
; ── Brick   28/60  [YELLOW]  col=  3  row=  2  →  X=74.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X74.000 Y150.000 E0.0500 F2000 ; position over col=3 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P47 R0 Q47 S0  ; progress 47%
; ── Brick   29/60  [YELLOW]  col=  4  row=  2  →  X=82.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X82.000 Y150.000 E0.0500 F2000 ; position over col=4 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P48 R0 Q48 S0  ; progress 48%
; ── Brick   30/60  [YELLOW]  col=  5  row=  2  →  X=90.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X90.000 Y150.000 E0.0500 F2000 ; position over col=5 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P50 R0 Q50 S0  ; progress 50%
; ── Brick   31/60  [RED   ]  col=  6  row=  2  →  X=98.0  Z=24.2 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X98.000 Y150.000 E0.0500 F2000 ; position over col=6 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P52 R0 Q52 S0  ; progress 52%
; ── Brick   32/60  [YELLOW]  col=  7  row=  2  →  X=106.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X106.000 Y150.000 E0.0500 F2000 ; position over col=7 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P53 R0 Q53 S0  ; progress 53%
; ── Brick   33/60  [RED   ]  col=  8  row=  2  →  X=114.0  Z=24.2 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X114.000 Y150.000 E0.0500 F2000 ; position over col=8 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P55 R0 Q55 S0  ; progress 55%
; ── Brick   34/60  [YELLOW]  col=  9  row=  2  →  X=122.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X122.000 Y150.000 E0.0500 F2000 ; position over col=9 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P57 R0 Q57 S0  ; progress 57%
; ── Brick   35/60  [RED   ]  col= 10  row=  2  →  X=130.0  Z=24.2 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X130.000 Y150.000 E0.0500 F2000 ; position over col=10 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P58 R0 Q58 S0  ; progress 58%
; ── Brick   36/60  [YELLOW]  col= 11  row=  2  →  X=138.0  Z=24.2 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X138.000 Y150.000 E0.0500 F2000 ; position over col=11 row=2 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z48.700 F800 ; slow approach (6 mm above target)
G1 Z42.700 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

;LAYER_CHANGE
;Z:33.800
;HEIGHT:9.600
; --- Layer 4/5 ---
M73 P60 R0 Q60 S0  ; progress 60%
; ── Brick   37/60  [YELLOW]  col=  0  row=  3  →  X=50.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X50.000 Y150.000 E0.0500 F2000 ; position over col=0 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P62 R0 Q62 S0  ; progress 62%
; ── Brick   38/60  [RED   ]  col=  1  row=  3  →  X=58.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X58.000 Y150.000 E0.0500 F2000 ; position over col=1 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P63 R0 Q63 S0  ; progress 63%
; ── Brick   39/60  [RED   ]  col=  2  row=  3  →  X=66.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X66.000 Y150.000 E0.0500 F2000 ; position over col=2 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P65 R0 Q65 S0  ; progress 65%
; ── Brick   40/60  [YELLOW]  col=  3  row=  3  →  X=74.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X74.000 Y150.000 E0.0500 F2000 ; position over col=3 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P67 R0 Q67 S0  ; progress 67%
; ── Brick   41/60  [RED   ]  col=  4  row=  3  →  X=82.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X82.000 Y150.000 E0.0500 F2000 ; position over col=4 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P68 R0 Q68 S0  ; progress 68%
; ── Brick   42/60  [YELLOW]  col=  5  row=  3  →  X=90.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X90.000 Y150.000 E0.0500 F2000 ; position over col=5 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P70 R0 Q70 S0  ; progress 70%
; ── Brick   43/60  [RED   ]  col=  6  row=  3  →  X=98.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X98.000 Y150.000 E0.0500 F2000 ; position over col=6 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P72 R0 Q72 S0  ; progress 72%
; ── Brick   44/60  [YELLOW]  col=  7  row=  3  →  X=106.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X106.000 Y150.000 E0.0500 F2000 ; position over col=7 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P73 R0 Q73 S0  ; progress 73%
; ── Brick   45/60  [RED   ]  col=  8  row=  3  →  X=114.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X114.000 Y150.000 E0.0500 F2000 ; position over col=8 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P75 R0 Q75 S0  ; progress 75%
; ── Brick   46/60  [YELLOW]  col=  9  row=  3  →  X=122.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X122.000 Y150.000 E0.0500 F2000 ; position over col=9 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P77 R0 Q77 S0  ; progress 77%
; ── Brick   47/60  [RED   ]  col= 10  row=  3  →  X=130.0  Z=33.8 ──
;    [pick-up  RED]
;TYPE:Travel
G0 X0.000 Y0.000 F6000 ; move over RED dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X130.000 Y150.000 E0.0500 F2000 ; position over col=10 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P78 R0 Q78 S0  ; progress 78%
; ── Brick   48/60  [YELLOW]  col= 11  row=  3  →  X=138.0  Z=33.8 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X138.000 Y150.000 E0.0500 F2000 ; position over col=11 row=3 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z58.300 F800 ; slow approach (6 mm above target)
G1 Z52.300 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

;LAYER_CHANGE
;Z:43.400
;HEIGHT:9.600
; --- Layer 5/5 ---
M73 P80 R0 Q80 S0  ; progress 80%
; ── Brick   49/60  [YELLOW]  col=  0  row=  4  →  X=50.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X50.000 Y150.000 E0.0500 F2000 ; position over col=0 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P82 R0 Q82 S0  ; progress 82%
; ── Brick   50/60  [YELLOW]  col=  1  row=  4  →  X=58.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X58.000 Y150.000 E0.0500 F2000 ; position over col=1 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P83 R0 Q83 S0  ; progress 83%
; ── Brick   51/60  [YELLOW]  col=  2  row=  4  →  X=66.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X66.000 Y150.000 E0.0500 F2000 ; position over col=2 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P85 R0 Q85 S0  ; progress 85%
; ── Brick   52/60  [YELLOW]  col=  3  row=  4  →  X=74.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X74.000 Y150.000 E0.0500 F2000 ; position over col=3 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P87 R0 Q87 S0  ; progress 87%
; ── Brick   53/60  [YELLOW]  col=  4  row=  4  →  X=82.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X82.000 Y150.000 E0.0500 F2000 ; position over col=4 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P88 R0 Q88 S0  ; progress 88%
; ── Brick   54/60  [YELLOW]  col=  5  row=  4  →  X=90.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X90.000 Y150.000 E0.0500 F2000 ; position over col=5 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P90 R0 Q90 S0  ; progress 90%
; ── Brick   55/60  [YELLOW]  col=  6  row=  4  →  X=98.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X98.000 Y150.000 E0.0500 F2000 ; position over col=6 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P92 R0 Q92 S0  ; progress 92%
; ── Brick   56/60  [YELLOW]  col=  7  row=  4  →  X=106.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X106.000 Y150.000 E0.0500 F2000 ; position over col=7 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P93 R0 Q93 S0  ; progress 93%
; ── Brick   57/60  [YELLOW]  col=  8  row=  4  →  X=114.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X114.000 Y150.000 E0.0500 F2000 ; position over col=8 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P95 R0 Q95 S0  ; progress 95%
; ── Brick   58/60  [YELLOW]  col=  9  row=  4  →  X=122.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X122.000 Y150.000 E0.0500 F2000 ; position over col=9 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P97 R0 Q97 S0  ; progress 97%
; ── Brick   59/60  [YELLOW]  col= 10  row=  4  →  X=130.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X130.000 Y150.000 E0.0500 F2000 ; position over col=10 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P98 R0 Q98 S0  ; progress 98%
; ── Brick   60/60  [YELLOW]  col= 11  row=  4  →  X=138.0  Z=43.4 ──
;    [pick-up  YELLOW]
;TYPE:Travel
G0 X30.000 Y0.000 F6000 ; move over YELLOW dispenser
G0 Z5.000 F800 ; descend to grab height
G4 P500  ; dwell — let block seat in socket
G0 Z80.000 F2000 ; rise with brick (carry speed)

;    [travel to brick]
;TYPE:Custom
G1 X138.000 Y150.000 E0.0500 F2000 ; position over col=11 row=4 (carry speed)
G92 E0   ; reset E after travel mark

;    [place]
;TYPE:Travel
G0 Z67.900 F800 ; slow approach (6 mm above target)
G1 Z61.900 F150 ; push brick onto studs
G4 P200  ; dwell 200 ms — ensure engagement
;TYPE:Travel
G0 Z80.000 F6000 ; retract to safe height

M73 P100 R0 Q100 S0  ; progress: 100%

; ── All bricks placed ──────────────────────────────────────
;TYPE:Travel
G1 Z90.000 F720 ; raise nozzle clear of wall
; NOTE: M104 S0 / M140 S0 / M107 omitted — no hotend/bed on this machine
M84          ; disable steppers

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_separation = 0
; brim_type = no_brim
; brim_width = 0
; clip_multipart_objects = 1
; colorprint_heights = 
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; draft_shield_distance = 10
; duplicate_distance = 6
; elefant_foot_compensation = 0
; elefant_foot_min_width = 0.2
; end_gcode = M84
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extrusion_multiplier = 1
; extrusion_width = 8.00
; fan_always_on = 1
; fan_below_layer_time = 100
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 0
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 30
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = 1
; infill_acceleration = 0
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 9.6000
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}.gcode
; overhangs = 1
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; post_process = 
; print_settings_id = 
; resolution = 0
; seam_position = aligned
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slowdown_below_layer_time = 5
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; thick_bridges = 1
; thin_walls = 1
; threads = 4
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.45
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 120
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; xy_size_compensation = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = 
; filament_settings_id = 
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; first_layer_bed_temperature = 0
; first_layer_temperature = 0
; max_fan_speed = 100
; min_fan_speed = 35
; temperature = 0
; before_layer_gcode = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 0
; between_objects_gcode = 
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_filament_profile = 
; default_print_profile = 
; end_filament_gcode = "; Filament-specific end gcode"
; extra_loading_move = -2
; extruder_colour = #FF8000
; extruder_offset = 0x0
; high_current_on_filament_swap = 0
; host_type = octoprint
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 1500,1500
; machine_max_acceleration_x = 1000,1000
; machine_max_acceleration_y = 1000,1000
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,200
; machine_max_feedrate_y = 200,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 1.5,1.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_layer_height = 9.6000
; max_print_height = 210
; min_layer_height = 9.6000
; nozzle_diameter = 0.4
; parking_pos_retraction = 92
; printer_model = MK3S
; printer_notes = 
; printer_settings_id = 
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = Prusa Research
; remaining_times = 1
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; silent_mode = 0
; single_extruder_multi_material = 0
; start_filament_gcode = "; Filament gcode"
; start_gcode = G28 W
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; prusaslicer_config = end